import express, { Request, Response } from "express";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

// .env কনফিগারেশন
dotenv.config();

const router = express.Router();

// Gemini ক্লায়েন্ট ইনিশিয়ালাইজেশন
const gemini = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });


/**
 * 🤖 মিটিং ট্রান্সক্রিপ্ট থেকে Gemini API ব্যবহার করে সারসংক্ষেপ তৈরি করে।
 * @param transcript - মিটিংয়ের সম্পূর্ণ টেক্সট ট্রান্সক্রিপ্ট।
 * @returns {Promise<string>} - মিটিংয়ের সারসংক্ষেপ বা এরর মেসেজ।
 */
async function generateSummary(transcript: string): Promise<string> {
    
    // ইনপুট ভ্যালিডেশন
    if (!transcript || typeof transcript !== 'string' || transcript.trim().length === 0) {
        // একটি স্পষ্ট এরর থ্রো করুন, যা রাউটে ধরা পড়বে।
        throw new Error("Invalid or empty transcript provided.");
    }

    // প্রম্পট ইঞ্জিনিয়ারিং
    const prompt = `Please act as a professional meeting minutes generator. Summarize the following meeting transcript, focusing explicitly on:
1. **Summary:** A brief overview of the discussion.
2. **Key Decisions:** Any final decisions or agreements made.
3. **Action Items:** A list of tasks assigned, including who is responsible (if available) and the next step.

TRANSCRIPT:\n\n${transcript}`;

    try {
        const result = await gemini.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt
        });

        return result.text.trim() || "Summary could not be generated by the AI.";

    } catch (err) {
        // API স্তরের ত্রুটি লগ ও থ্রো করুন
        console.error("Gemini API Error:", (err as Error).message);
        throw new Error("Failed to communicate with the AI service.");
    }
}


/**
 * 🔗 রাউট: /api/ai-summary
 * ট্রান্সক্রিপ্ট গ্রহণ করে এবং AI সামারি ফেরত পাঠায়।
 */
router.post("/ai-summary", async (req: Request, res: Response) => {
    const { transcript } = req.body;
    
    // 🚦 ইনপুট ভ্যালিডেশন (ট্রান্সক্রিপ্ট বডিতে আছে কিনা)
    if (!transcript) {
        return res.status(400).json({ error: "Transcript is required in the request body." });
    }

    try {
        const summary = await generateSummary(transcript);
        
        // সফল হলে সামারি ফেরত দিন
        return res.json({ summary });

    } catch (error) {
        // generateSummary ফাংশন থেকে আসা এরর হ্যান্ডেল করুন
        const errorMessage = (error as Error).message;
        
        if (errorMessage.includes("Invalid or empty transcript")) {
            return res.status(400).json({ error: errorMessage });
        }
        
        // অন্যান্য সার্ভার/API ত্রুটি
        console.error("Summary Route Error:", errorMessage);
        return res.status(500).json({ error: "Internal Server Error: Could not generate summary." });
    }
});

export default router;